"""create m_document_rules table

Revision ID: 2fc4ea282b77
Revises: d89fd3ec75f7
Create Date: 2025-05-29 19:50:25.301392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc4ea282b77'
down_revision: Union[str, None] = 'd89fd3ec75f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 