"""create m_entity_document_logs table

Revision ID: 34b88e8c81ad
Revises: cabe66628435
Create Date: 2025-05-30 17:03:38.192619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b88e8c81ad'
down_revision: Union[str, None] = 'cabe66628435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 