"""create parameters and attributes

Revision ID: 38dd3083aa9c
Revises: 5f926255ac28
Create Date: 2025-05-27 13:43:27.827106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dd3083aa9c'
down_revision: Union[str, None] = '5f926255ac28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Hace referecnia al nombre del atributo.'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Hace referencia la descripcion.'),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_attributes_id'), 'm_attributes', ['id'], unique=False)
    op.create_table('m_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Hace referencia al nombre del parametro.'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Hace referencia a la descripcion del parametro.'),
    sa.Column('state', sa.Integer(), nullable=False, comment='Hace referencia a si el estado esta activo (1) o no(0).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_parameters_id'), 'm_parameters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_parameters_id'), table_name='m_parameters')
    op.drop_table('m_parameters')
    op.drop_index(op.f('ix_m_attributes_id'), table_name='m_attributes')
    op.drop_table('m_attributes')
    # ### end Alembic commands ### 