"""add description column to stage

Revision ID: 5f926255ac28
Revises: 1ee5904f0e93
Create Date: 2025-05-26 16:59:26.704345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f926255ac28'
down_revision: Union[str, None] = '1ee5904f0e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_stages', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_stages', 'description')
    # ### end Alembic commands ### 