"""Agrego modelo nuevo y modifico modelo existente

Revision ID: 7bd207c4159d
Revises: dc25f33f309f
Create Date: 2025-05-21 20:35:25.345639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd207c4159d'
down_revision: Union[str, None] = 'dc25f33f309f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_entity_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['m_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_entity_types_id'), 'm_entity_types', ['id'], unique=False)
    op.alter_column('m_projects', 'state',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_m_projects_id'), 'm_projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_projects_id'), table_name='m_projects')
    op.alter_column('m_projects', 'state',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_m_entity_types_id'), table_name='m_entity_types')
    op.drop_table('m_entity_types')
    # ### end Alembic commands ### 