"""Add FK to entity_document_id

Revision ID: b4e15d98dc0f
Revises: 99e1a53304f7
Create Date: 2025-05-31 15:28:53.913582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e15d98dc0f'
down_revision: Union[str, None] = '99e1a53304f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_entity_document_logs', sa.Column('entity_document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'm_entity_document_logs', 'm_entity_documents', ['entity_document_id'], ['id'])
    op.alter_column('m_entity_documents', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Hace referencia al usario de creacion.')
    op.add_column('o_notifications', sa.Column('entity_document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'o_notifications', 'm_entity_documents', ['entity_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'o_notifications', type_='foreignkey')
    op.drop_column('o_notifications', 'entity_document_id')
    op.alter_column('m_entity_documents', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Hace referencia al usario de creacion.')
    op.drop_constraint(None, 'm_entity_document_logs', type_='foreignkey')
    op.drop_column('m_entity_document_logs', 'entity_document_id')
    # ### end Alembic commands ### 