"""create m_document_rules table

Revision ID: cabe66628435
Revises: 2fc4ea282b77
Create Date: 2025-05-29 19:51:00.869406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabe66628435'
down_revision: Union[str, None] = '2fc4ea282b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_document_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Hace referencia al nombre del parametro.'),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False, comment='Hace referencia al tipo de documento.'),
    sa.Column('entity_type_id', sa.Integer(), nullable=False, comment='Hace referencia al tipo de entidad.'),
    sa.Column('stage_id', sa.Integer(), nullable=False, comment='Hace referencia a la etapa.'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Hace referencia a la descripcion del parametro.'),
    sa.Column('allowed_file_type', sa.JSON(), nullable=True, comment='Hace referencia al tipo de archivo.'),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('max_file_size', sa.Integer(), nullable=True, comment='Tamaño del archivo a cargar.'),
    sa.Column('state', sa.Integer(), nullable=False, comment='Hace referencia a si el estado esta activo (1) o no(0).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['m_attributes.id'], ),
    sa.ForeignKeyConstraint(['entity_type_id'], ['m_entity_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['m_projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['m_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_document_rules_id'), 'm_document_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_document_rules_id'), table_name='m_document_rules')
    op.drop_table('m_document_rules')
    # ### end Alembic commands ### 