"""create m_entity_documents table

Revision ID: d658bb7e54a2
Revises: cabe66628435
Create Date: 2025-05-30 21:48:58.205329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd658bb7e54a2'
down_revision: Union[str, None] = 'cabe66628435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_entity_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='Hace referencia al id del proyecto.'),
    sa.Column('document_type_id', sa.Integer(), nullable=False, comment='Hace refenrecia al id del tipo de documento.'),
    sa.Column('entity_type_id', sa.Integer(), nullable=False, comment='Hace referencia la tipo de entidad.'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='Hace referencia al id de la entidad externa (estudiante o deportista).'),
    sa.Column('stage_id', sa.Integer(), nullable=False, comment='Hace referencia a la Etapa.'),
    sa.Column('file_url', sa.String(length=100), nullable=True, comment='Hace referencia a la ruta de S3.'),
    sa.Column('file_extension', sa.String(length=100), nullable=True, comment='Hace referencia a la extension.'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='Hace referencia al tamaño del archivo.'),
    sa.Column('mime_type', sa.Integer(), nullable=True, comment='Hace referencia al tipo minimo.'),
    sa.Column('upload_device', sa.String(length=100), nullable=True, comment='Subir a dispositivo.'),
    sa.Column('upload_ip', sa.String(length=100), nullable=True, comment='Ip del dispositivo.'),
    sa.Column('document_status_id', sa.Integer(), nullable=False, comment='Hace refenrecia al estado del documento.'),
    sa.Column('observations', sa.String(length=100), nullable=True, comment='Hace referencia a la observacion.'),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='Hace referencia al usario de creacion.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_status_id'], ['m_attributes.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['m_attributes.id'], ),
    sa.ForeignKeyConstraint(['entity_type_id'], ['m_entity_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['m_projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['m_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_entity_documents_id'), 'm_entity_documents', ['id'], unique=False)
    op.alter_column('m_attributes', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre del atributo',
               existing_comment='Hace referecnia al nombre del atributo.',
               existing_nullable=False)
    op.alter_column('m_attributes', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='Descripción',
               existing_comment='Hace referencia la descripcion.',
               existing_nullable=True)
    op.alter_column('m_attributes', 'parameter_id',
               existing_type=sa.INTEGER(),
               comment='Parámetro principal',
               existing_comment='Hace referencia parámetro principal (id de parameters).',
               existing_nullable=False)
    op.alter_column('m_attributes', 'reference',
               existing_type=sa.VARCHAR(length=200),
               comment='Referencia',
               existing_comment='Hace referencia a la descripcion del parametro.',
               existing_nullable=True)
    op.alter_column('m_attributes', 'state',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Hace referencia a si el estado esta activo (1) o no(0).',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Hace referencia al nombre del parámetro.',
               existing_comment='Hace referencia al nombre del parametro.',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'document_type_id',
               existing_type=sa.INTEGER(),
               comment='Tipo de documento',
               existing_comment='Hace referencia al tipo de documento.',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'entity_type_id',
               existing_type=sa.INTEGER(),
               comment='Tipo de entidad',
               existing_comment='Hace referencia al tipo de entidad.',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'stage_id',
               existing_type=sa.INTEGER(),
               comment='Etapa',
               existing_comment='Hace referencia a la etapa.',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='Descripción',
               existing_comment='Hace referencia a la descripcion del parametro.',
               existing_nullable=True)
    op.alter_column('m_document_rules', 'allowed_file_type',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Tipo de archivo permitido',
               existing_comment='Hace referencia al tipo de archivo.',
               existing_nullable=True)
    op.alter_column('m_document_rules', 'max_file_size',
               existing_type=sa.INTEGER(),
               comment='Tamaño máximo del archivo',
               existing_comment='Tamaño del archivo a cargar.',
               existing_nullable=True)
    op.alter_column('m_document_rules', 'state',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Hace referencia a si el estado esta activo (1) o no(0).',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_document_rules', 'state',
               existing_type=sa.INTEGER(),
               comment='Hace referencia a si el estado esta activo (1) o no(0).',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'max_file_size',
               existing_type=sa.INTEGER(),
               comment='Tamaño del archivo a cargar.',
               existing_comment='Tamaño máximo del archivo',
               existing_nullable=True)
    op.alter_column('m_document_rules', 'allowed_file_type',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Hace referencia al tipo de archivo.',
               existing_comment='Tipo de archivo permitido',
               existing_nullable=True)
    op.alter_column('m_document_rules', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='Hace referencia a la descripcion del parametro.',
               existing_comment='Descripción',
               existing_nullable=True)
    op.alter_column('m_document_rules', 'stage_id',
               existing_type=sa.INTEGER(),
               comment='Hace referencia a la etapa.',
               existing_comment='Etapa',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'entity_type_id',
               existing_type=sa.INTEGER(),
               comment='Hace referencia al tipo de entidad.',
               existing_comment='Tipo de entidad',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'document_type_id',
               existing_type=sa.INTEGER(),
               comment='Hace referencia al tipo de documento.',
               existing_comment='Tipo de documento',
               existing_nullable=False)
    op.alter_column('m_document_rules', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Hace referencia al nombre del parametro.',
               existing_comment='Hace referencia al nombre del parámetro.',
               existing_nullable=False)
    op.alter_column('m_attributes', 'state',
               existing_type=sa.INTEGER(),
               comment='Hace referencia a si el estado esta activo (1) o no(0).',
               existing_nullable=False)
    op.alter_column('m_attributes', 'reference',
               existing_type=sa.VARCHAR(length=200),
               comment='Hace referencia a la descripcion del parametro.',
               existing_comment='Referencia',
               existing_nullable=True)
    op.alter_column('m_attributes', 'parameter_id',
               existing_type=sa.INTEGER(),
               comment='Hace referencia parámetro principal (id de parameters).',
               existing_comment='Parámetro principal',
               existing_nullable=False)
    op.alter_column('m_attributes', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='Hace referencia la descripcion.',
               existing_comment='Descripción',
               existing_nullable=True)
    op.alter_column('m_attributes', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Hace referecnia al nombre del atributo.',
               existing_comment='Nombre del atributo',
               existing_nullable=False)
    op.drop_index(op.f('ix_m_entity_documents_id'), table_name='m_entity_documents')
    op.drop_table('m_entity_documents')
    # ### end Alembic commands ### 