"""initial migration

Revision ID: d89fd3ec75f7
Revises: 
Create Date: 2025-05-29 18:45:54.190416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89fd3ec75f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Hace referencia al nombre del parametro.'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Hace referencia a la descripcion del parametro.'),
    sa.Column('state', sa.Integer(), nullable=False, comment='Hace referencia a si el estado esta activo (1) o no(0).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_parameters_id'), 'm_parameters', ['id'], unique=False)
    op.create_table('m_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_projects_id'), 'm_projects', ['id'], unique=False)
    op.create_table('m_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Hace referecnia al nombre del atributo.'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='Hace referencia la descripcion.'),
    sa.Column('parameter_id', sa.Integer(), nullable=False, comment='Hace referencia parámetro principal (id de parameters).'),
    sa.Column('reference', sa.String(length=200), nullable=True, comment='Hace referencia a la descripcion del parametro.'),
    sa.Column('state', sa.Integer(), nullable=False, comment='Hace referencia a si el estado esta activo (1) o no(0).'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['m_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_attributes_id'), 'm_attributes', ['id'], unique=False)
    op.create_table('m_entity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['m_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_entity_types_id'), 'm_entity_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m_entity_types_id'), table_name='m_entity_types')
    op.drop_table('m_entity_types')
    op.drop_index(op.f('ix_m_attributes_id'), table_name='m_attributes')
    op.drop_table('m_attributes')
    op.drop_index(op.f('ix_m_projects_id'), table_name='m_projects')
    op.drop_table('m_projects')
    op.drop_index(op.f('ix_m_parameters_id'), table_name='m_parameters')
    op.drop_table('m_parameters')
    # ### end Alembic commands ### 