class GlobalMessages:
    ERROR_VALIDATION = "Error de validación"
    ERROR_CREATED = "Error al crear el registro"
    ERROR_UPDATED = "Error al actualizar el registro"
    ERROR_DELETED = "Error al eliminar el registro"
    ERROR_GET = "Error al obtener el registro"
    ERROR_GET_ALL = "Error al obtener todos los registros"
    ERROR_INTERNAL = "Error interno del servidor"
    ERROR_UNAUTHORIZED = "No autorizado"
    ERROR_FORBIDDEN = "Prohibido"
    ERROR_NOT_FOUND = "No encontrado"
    ERROR_METHOD_NOT_ALLOWED = "Método no permitido"
    ERROR_CONFLICT = "Conflicto"
    ERROR_TOO_MANY_REQUESTS = "Demasiadas solicitudes"